version: "3"

volumes:
  pendulum-app-redis:
  pendulum-app-rabbitmq: 
networks:
  umbrella-net:
    name: "umbrella-net"
    external: false
name: pendulum-services
services:
  pendulum-app-orchestrator:
    image: azguerrero/elixir-pendulum-app
    restart: on-failure
    depends_on: 
      - pendulum-app-rabbitmq
      - pendulum-app-executor-0
      - pendulum-app-executor-1
      - pendulum-app-executor-2
      - pendulum-app-executor-3
      - pendulum-app-executor-4
    hostname: orchestrator0.pendulum.app.com
    environment:
      - APP_TYPE=orchestrator
    volumes:
      - ../:/pendulum-app-orchestrator
    networks:
      - umbrella-net
  pendulum-app-executor-0:
    image: azguerrero/elixir-pendulum-app
    hostname: executor0.pendulum.app.com
    environment:
      - APP_TYPE=executor
    volumes:
      - ../:/pendulum-app-orchestrator
    networks:
      - umbrella-net
  pendulum-app-executor-1:
    image: azguerrero/elixir-pendulum-app
    hostname: executor1.pendulum.app.com
    environment:
      - APP_TYPE=executor
    volumes:
      - ../:/pendulum-app-orchestrator
    networks:
      - umbrella-net
  pendulum-app-executor-2:
    image: azguerrero/elixir-pendulum-app
    hostname: executor2.pendulum.app.com
    environment:
      - APP_TYPE=executor
    volumes:
      - ../:/pendulum-app-orchestrator
    networks:
      - umbrella-net
  pendulum-app-executor-3:
    image: azguerrero/elixir-pendulum-app
    hostname: executor3.pendulum.app.com
    environment:
      - APP_TYPE=executor
    volumes:
      - ../:/pendulum-app-orchestrator
    networks:
      - umbrella-net
  pendulum-app-executor-4:
    image: azguerrero/elixir-pendulum-app
    hostname: executor4.pendulum.app.com
    environment:
      - APP_TYPE=executor
    volumes:
      - ../:/pendulum-app-orchestrator
    networks:
      - umbrella-net
  pendulum-app-redis:
    image: redis
    volumes:
      - pendulum-app-redis:/data
    expose:
      - 6379
    ports:
      - 6380:6379      
    restart: unless-stopped
    networks:
      - umbrella-net
  pendulum-app-rabbitmq:
    image: azguerrero/rabbitmq-deduplication
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin 
    volumes:
      - pendulum-app-rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - umbrella-net
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
 